### Course 2. Week 4. Task 1 "Бэггинг и случайный лес"

Загрузите датасет digits с помощью функции load_digits из sklearn.datasets и подготовьте матрицу признаков X и ответы на обучающей выборке y (вам потребуются поля data и target в объекте, который возвращает load_digits).

Для оценки качества далее нужно будет использовать cross_val_score из sklearn.cross_validation с параметром cv=10. Эта функция реализует k-fold cross validation c k равным значению параметра cv. Мы предлагаем использовать k=10, чтобы полученные оценки качества имели небольшой разброс, и было проще проверить полученные ответы. На практике же часто хватает и k=5. Функция cross_val_score будет возвращать numpy.ndarray, в котором будет k чисел - качество в каждом из k экспериментов k-fold cross validation. Для получения среднего значения (которое и будет оценкой качества работы) вызовите метод .mean() у массива, который возвращает cross_val_score.

С небольшой вероятностью вы можете натолкнуться на случай, когда полученное вами качество в каком-то из пунктов не попадет в диапазон, заданный для правильных ответов - в этом случае попробуйте перезапустить ячейку с cross_val_score несколько раз и выбрать наиболее «типичное» значение. Если это не помогает, то где-то была допущена ошибка.

Если вам захочется ускорить вычисление cross_val_score - можете попробовать использовать параметр n_jobs, но будьте осторожны: в одной из старых версий sklearn была ошибка, которая приводила к неверному результату работы cross_val_score при задании n_jobs отличным от 1. Сейчас такой проблемы возникнуть не должно, но проверить, что все в порядке, не будет лишним.

In [35]:
import numpy as np
import matplotlib.pyplot as plt 
from sklearn import datasets, model_selection, metrics, tree ,ensemble

%pylab inline
#from matplotlib.colors import ListedColormap

Populating the interactive namespace from numpy and matplotlib


In [22]:
digits = datasets.load_digits()
#print(digits.data.shape)

#plt.gray() 
#plt.matshow(digits.images[3]) 
#plt.show() 

X = digits.data
y = digits.target

print X
print y

print type(digits.data)
print type(digits.target)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]
<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


1. Создайте DecisionTreeClassifier с настройками по умолчанию и измерьте качество его работы с помощью cross_val_score. Эта величина и будет ответом в пункте 1.

In [36]:
dtc = tree.DecisionTreeClassifier(random_state=17)
cv_res_tree = model_selection.cross_val_score(dtc, X, y, cv=10)
print cv_res_tree
print
print 'Answer: ', np.mean(cv_res_tree)

[0.78918919 0.86338798 0.79558011 0.8        0.77094972 0.88268156
 0.89944134 0.8258427  0.84180791 0.8125    ]

Answer:  0.828138050976056


2. Воспользуйтесь BaggingClassifier из sklearn.ensemble, чтобы обучить бэггинг над DecisionTreeClassifier. Используйте в BaggingClassifier параметры по умолчанию, задав только количество деревьев равным 100. Качество классификации новой модели - ответ в пункте 2. Обратите внимание, как соотносится качество работы композиции решающих деревьев с качеством работы одного решающего дерева.

In [37]:
bcl = ensemble.BaggingClassifier(n_estimators=100)
cv_res_bag = model_selection.cross_val_score(bcl, X, y, cv=10)
print cv_res_bag
print
print 'Answer: ', np.mean(cv_res_bag)

[0.85405405 0.94535519 0.90607735 0.94444444 0.9273743  0.98882682
 0.95530726 0.90449438 0.8700565  0.92613636]

Answer:  0.9222126660543873


3.Теперь изучите параметры BaggingClassifier и выберите их такими, чтобы каждый базовый алгоритм обучался не на всех d признаках, а на \sqrt{d} 
d
​	  случайных признаков. Качество работы получившегося классификатора - ответ в пункте 3. Корень из числа признаков - часто используемая эвристика в задачах классификации, в задачах регрессии же часто берут число признаков, деленное на три. Но в общем случае ничто не мешает вам выбирать любое другое число случайных признаков.

In [50]:
feat_num = X[0].size

bcl2 = ensemble.BaggingClassifier(n_estimators=100, max_features=int(sqrt(feat_num)))
cv_res_bag2 = model_selection.cross_val_score(bcl2, X, y, cv=10)
print cv_res_bag2
print
print 'Answer: ', np.mean(cv_res_bag2)

[0.88108108 0.96721311 0.93922652 0.92222222 0.94413408 0.9273743
 0.95530726 0.98876404 0.8700565  0.93181818]

Answer:  0.9327197303789662
